#!/bin/bash
function die {
    osascript -e "tell application (path to frontmost application as text) to display dialog \"$1\" buttons {\"OK\"} with icon stop"
    exit 1
}

RESOURCES_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../Resources"

IOHID_WRAP_DYLIB_PATH="$RESOURCES_DIR/iohid_wrap.dylib"

if [ ! -f "$IOHID_WRAP_DYLIB_PATH" ]; then
    die "$IOHID_WRAP_DYLIB_PATH could not be found"
fi

export DYLD_FORCE_FLAT_NAMESPACE=1
export DYLD_INSERT_LIBRARIES="$IOHID_WRAP_DYLIB_PATH"

EXE_PATH="./Contents/MacOS/RemotePlay"

APP_PATH="$RESOURCES_DIR/RemotePlay.app"
if [ ! -x "$APP_PATH/$EXE_PATH" ]; then
    APP_PATH="/Applications/RemotePlay.app"
fi

if [ ! -x "$APP_PATH/$EXE_PATH"  ]; then
    die "RemotePlay.app was not found in Resources nor in /Applications"
fi
exec "$APP_PATH/$EXE_PATH"
